language: java

dist: xenial

jdk: openjdk11

services:
  - xvfb

addons:
  sonarcloud:
    organization: "sreenu-reddy-1"
    token:
      secure: $SONAR_TOKEN


after_success:
  - mvn clean test jacoco:report coveralls:repoprt

install: true

cache:
  directories:
    - $HOME/.m2


script:
  - mvn clean verify jacoco:report coveralls:report sonar:sonar
