language: java
dist: xenial
jdk: openjdk11
services:
- xvfb
addons:
  sonarcloud:
    organization: sreenu-reddy
    token:
      secure: Q87ifwbtkrJOt3wKMMt0Xq5cZlAXaY6R/Ha9gPv4qqeRirlpl6cm4yMrClDvtJPsq+2Ry/iR8zBOiVM8F6bk9ZDDA3lNwvcgzCwf774ZL/gS5fUTJf1EMVt5NeqFviYBd/iRq12ZX+C51FsuAJbkg1B4Z7WVNzkJPhyIxdVc1fqYcuqbyhEKMHE2y5w0ITmCiNuBet+UPT3tPPcCqMAbgp7lFdkwKkID/aqrGCpyqHnfTyHFwG5xbe6c4nqPeynhxPud82zrbEY2oNdgbAatI5uijw7I/m919rsybow+dIJ7Ih9FY5DhUj9lWkSKR5durz2hm+ZUKPZbt2JayEpKZUTGXXFhT6ZUOVxdEVGjkiV7T9H3eFAWFJ6pOK7iX2LE6l4DmSz1yP6DoYI1DPyyQ+njVGYvg+agfNzj2GGNVQNPzDK35X2eHln9zj+8CVH5WRUfeWDuMeXyLy4abQz/x6ukKlCuRoI777x8a8FVhvgDS85Vfr3VB0lMqkh3CLltk3iLxvCDaB3O/j8eu8Gr/9+1lMH5E8/dO+fv58ysG4tT3RrMso32EZxg6zDPmW48S0IjGrpan807m5Y44QPRE3mQh2FMSnRWjBKY3W3MWutu3Sq7BoKhuzd6s05AcobV2MD9cXthWm5MKfvJ9qlK/9mPc7qzeP2SB91o9GawaFY=
after_success:
- mvn clean test jacoco:report coveralls:repoprt
install: true
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.sonar/cache"
script:
- mvn clean verify jacoco:report coveralls:report sonar:sonar -Dsonar.projectKey=sreenu-reddy_TestDrivenDevelopment
env:
  global:
    secure: hCCjknKueuiX86CFyUwo0CvueZuwd/voiRrQt62w5/i+1yZyx51fnLtGuzlMG06hfFF5Y+k3V5x7+csu8saxorMWqNc9/dYrqAP9txqLAxZT5WypJLGr2uiBPfnxBNGJ2uu77bIyR03XvT8K8kugzls75GQvT94mKG/1jt1YfYPxV650UK87vP7aCHdT4LqMLIKnnq8BXPkvafKTGvfSpu6Gk78TgQrlyHECXEP0ekaQxLWf8IpeR/hPL8xuyiVasWd8a8MuUW0vIs61mZ4O3QcGjc3/N2QBQjT2tCzT9KyDf2KE4BwPhZYx6O4cV7tWnLfOoUoB54UB1IG3IDanO32UBhPHGl1q9NJvPT+N+ft8P9N8zrVU6hPUxOsDkP7wTFtPcKDJT5T/FJ3mPEwy5A97FrAeYVXzRpVO+t9yMUB/mVvqpkZvlCeigposkNKKGWzAAk6fR361hFWTrAEOF47xRy74nfOLVCMIosyAiGvI/ozVqORQdRbDd7g3+oqojLoyAu2pgx6iHDtUW22O8FtvfbImdqdDlLvg6SdCdeo1YLIU7OjF0Z5SznIFqRhL4as2Kl2B5Ut351926TFHYQq2gLoAQknJY/e9+68mo8r6gXlT5xcXhcK7b/PqQOncVXBkYbO2MOAdakbkQZK9GknlaahwRyK4AZ1NYhnv3ec=
