spring:
  datasource:
    url: jdbc:mysql://localhost:3303/TDD_prod
    username: TDD_prod_user
    password: guru
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false